variable "pri_sec" { }
variable "vnet_name" { }
variable "rg_name" { }
variable "cidr_block" { }
variable "org_tla" { }
variable "stage" { }
variable "location" { }
variable "description" { }
variable "billing_code" { }
